name: mlui

services:
  app:
    container_name: app-dev
    build:
      context: ./
      target: dev
      args:
        - APP_ENV=DEV
    image: mlui-dev:latest
    ports:
      - "8501:8501"
    volumes:
      - ./src/:/usr/src/app/src
      - ./docs/:/usr/src/app/docs
      - ./tests/:/usr/src/app/tests
      - ./poetry.lock:/usr/src/app/poetry.lock
      - ./pyproject.toml:/usr/src/app/pyproject.toml
