name: machine-learning-ui
channels:
  - conda-forge
dependencies:
  - python=3.10
  - bqplot=0.12.*
  - ipydatagrid=1.1.*
  - ipyfilechooser=0.6.*
  - ipywidgets=8.0.*
  - jupyterlab=3.5.*
  - numpy=1.23.*
  - pandas=1.5.*
  - pydot=1.4.*
  - scikit-learn=1.1.*
  - voila=0.4.*
  - pip=22.2.*
  - pip:
      - tensorflow==2.10.*
      - tensorflow-addons==0.18.*
